### ISSUE TITLE
feat: show terms and conditions during signup

### ISSUE THREAD

**Issue by aayushchugh** [is-it-ayush/athing#19]
When we click on the `terms and conditions` it doesn't show us any details. We can either create a modal with our terms and conditions or we can redirect user to another page.

![image](https://github.com/is-it-ayush/athing/assets/69336518/2a21aab0-6043-4559-aa42-de3c14a4b3fa)

**Comment by is-it-ayush** [comment]
Ideally, `terms & conditions` would need to be referenced on other websites as well (ex, `developers.x.com` requires it for authentication with twitter). I think a dedicated page such as `www.example.com/terms-and-conditions` would be better. We can either,
1. have both the popup modal and `www.example.com/terms-and-conditions` page.
2. have only the `www.example.com/terms-and-conditions` page and open it with `_blank` target which the user can navigate back from.

I'll provide you the terms and conditions that you can put there. What do you think?

**Comment by aayushchugh** [comment]
Personally, a dedicated page looks like a better option because `terms & conditions` have long content, so it will be easier for the user to navigate through them on a dedicated page

**Comment by is-it-ayush** [comment]
You're right! Let's do a simple dedicated page for terms and conditions. You wanna work on it @aayushchugh?

**Comment by aayushchugh** [comment]
@is-it-ayush you can take this
